### ISSUE TITLE
运行示例报错

### ISSUE THREAD

**Issue by wangkang123123** [fan-ziqi/robot_lab#1]
![微信图片_20240712114016](https://github.com/user-attachments/assets/6c957a33-e01d-489c-8390-4a5607fe9902)

例子都运行不起来，求解

**Comment by fan-ziqi** [comment]
This issue occurred because the parent class set rewards with a weight of 0 to None. When the subclass attempted to override a nonexistent weight, it caused errors. This problem has been fixed in commit 5718c51.
