### ISSUE TITLE
Mujoco Sim2Sim

### ISSUE THREAD

**Issue by chenyunzhanggit** [fan-ziqi/robot_lab#16]
Hello, I want know if you have done Sim2Sim in Mujoco successfully by the trained policy.
Thanks!

**Comment by fan-ziqi** [comment]
Mujoco support is not planned.
---- Replied Message ----
From ***@***.***> Date 09/24/2024 19:00 To ***@***.***> Cc ***@***.***> Subject [fan-ziqi/robot_lab] Mujoco Sim2Sim (Issue #16) 
Hello, I want know if you have done Sim2Sim in Mujoco successfully by the trained policy.
Thanks!

**Comment by chenyunzhanggit** [comment]
Thanks
