### ISSUE TITLE
[Proposal] "terminal_amp_states"参数赋值位置的问题

### ISSUE THREAD

**Issue by Huisouan** [fan-ziqi/robot_lab#18]
##问题描述
在
exts/robot_lab/robot_lab/tasks/locomotion/velocity/config/unitree_a1_amp/env/manager_based_rl_amp_env.py
代码中，
terminal_amp_states = self.get_amp_observations()[reset_env_ids]
的赋值应是否该位于环境重置
self._reset_idx(reset_env_ids)
之前进行?

**Comment by fan-ziqi** [comment]
感谢指正! 在 1df1b4aa47aad7eda02b67bb5e16230f7a1ecd33 中修复此问题.
