### ISSUE TITLE
About the traning script didn't work.

### ISSUE THREAD

**Issue by gaiyi7788** [fan-ziqi/robot_lab#3]
Thank you for your outstanding work. 

I tried to run the training script but it didn't work. 

`python scripts/rsl_rl/train.py --task RobotLab-Isaac-Velocity-Flat-Unitree-H1-v0 --headless`

After I run this script,  output is shown below and there are no new changes,

![2024-07-17 10-23-41 的屏幕截图](https://github.com/user-attachments/assets/2b5eda3e-ac7c-4747-b688-832500fa75d6)

I'm running on a single 4090. Could you please give me some advice?

Best whishes!

**Comment by fan-ziqi** [comment]
The program did not report any errors, maybe it‘s downloading H1 assets.

**Comment by gaiyi7788** [comment]
> The program did not report any errors, maybe it‘s downloading H1 assets.

Thanks for the timely response! I will close this issue after further attempts.
