### ISSUE TITLE
No module named 'omni'

### ISSUE THREAD

**Issue by zQqingqing** [fan-ziqi/robot_lab#4]
After completing 
python -m pip install -e ./exts/robot_lab 
I ran
python scripts/rsl_rl/train.py --task RobotLab-Isaac-Velocity-Flat-Anymal-D-v0 --headless  

Traceback (most recent call last):
  File "F:\Omniverse\pkg\IsaacLab\robot_lab-main\scripts\rsl_rl\train.py", line 7, in <module>
    from omni.isaac.lab.app import AppLauncher
ModuleNotFoundError: No module named 'omni'

**Comment by fan-ziqi** [comment]
Have you install IsaacLab properly?

**Comment by zQqingqing** [comment]
> Have you install IsaacLab properly?

I have installed IsaacLab through Omniverse Launch, but I have to pip install isaacsim again in my conda env to solve this error.
following https://github.com/isaac-sim/IsaacLab/issues/516#issuecomment-2226378529. 
I guess this cound be my configuration problem and is not related to your code.
However I finally run this code successfully :)
